name: Create Archive
on: [push]

permissions:
  contents: write  # Grants read and write permissions to repository contents

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Ensure clean working directory
        run: |
          git fetch origin main
          git reset --hard origin/main
          rm -f release.zip

      - name: Archive repository (excluding certain files)
        run: |
          zip -r release.zip . -x "*.git*" "node_modules/*" ".editorconfig"

      - name: Push changes to remote
        run: |
          git add -A
          git diff --cached --quiet || (git commit -m "new pack" && git push --force)
