name: Create Archive
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Pull latest and remove old file from repo
        run: |
          git config --global user.name "KalpeGames"
          git config --global user.email "git@kalpe.games"
          git config pull.rebase false
          git pull
          rm -f release.zip

      - name: Archive repository (excluding certain files)
        run: |
          zip -r release.zip . -x "*.git*" "node_modules/*" ".editorconfig"

      - name: Push changes to remote
        run: |
          git add -A
          git commit -m "new pack"
          git push --force
